#!/bin/bash
SCRIPT_DIR=`dirname $(python -c "import os, sys; print os.path.realpath(\"$0\")")`
. ${SCRIPT_DIR}/config_bash
includes=""
objs=(`find ../*_c -name "*.o" -print`)
for i in ../*_c ; do
	includes="$includes -I $i"
done
case $1 in
	-lib)
		shift;
		main=""
		;;
	-main)
		shift;
		main="$1"
		;;
	*)
		main=_main
		;;
esac
if [[ $# == 0 ]]
then
	sources=(`find . -name "*.cpp" \! -name "${main}.cpp" -print`)
else
	sources=$@
fi
echo "${CXX} ${CXXFLAGS} -I ~/W/heptagon/lib/c $includes -c ${sources[*]}"
${CXX} ${CXXFLAGS} -I ~/W/heptagon/lib/c $includes -c ${sources[*]}
if [ ! -x "${main}.cpp" ]
then
	echo "${CXX} ${CXXFLAGS} -I ~/W/heptagon/lib/c ~/W/heptagon/lib/c/libdecades.a $includes ${objs[*]} ${sources[*]/.cpp/.o} "${main}.cpp""
	${CXX} ${CXXFLAGS} -I ~/W/heptagon/lib/c ~/W/heptagon/lib/c/libdecades.a $includes ${objs[*]} ${sources[*]/.cpp/.o} "${main}.cpp"
fi

