#!/bin/bash
includes=""
objs=`ls ../*_c/*.o 2> /dev/null`
for i in ../*_c ; do
	includes="$includes -I $i"
done
g++-mp-4.7 -std=c++11 -I ~/W/heptagon/lib/c ~/W/heptagon/lib/c/libdecades.a $includes $objs $@
